server:
  port: 8081

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/info?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    #username: root
    #password: "123456"
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  cloud:
    sentinel:
      transport:
        # 服务监控端口
        dashboard: localhost:8080
